name: CD -  Build Web and Deploy on GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: Install dependencies
        run: flutter pub get
      - name: Build web app
        run: |
          flutter build web  --web-renderer html --release
          #flutter build web --web-renderer canvaskit --release
          #flutter build web --release
      - name: Execute Service Worker command
        run: |
          sed -i '/index.html/d' build/web/flutter_service_worker.js
      - name: Deploy web app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          allow_empty_commit: true
